//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lr_fifteen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Абитуриенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public Абитуриенты()
        {
            this.Заявления = new HashSet<Заявления>();

            this.Оценки = new HashSet<Оценки>();
        }

        public int Код_абитуриента { get; set; }
        public string Фамилия { get; set; }

        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Статус { get; set; }
        public string Город { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public virtual ICollection<Заявления> Заявления { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public virtual ICollection<Оценки> Оценки { get; set; }
    }
}
