//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lr_fifteen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Экзамены
    {
        public int Код_экзамена { get; set; }
        public Nullable<int> Код_специальности { get; set; }
        public Nullable<int> Код_дисциплины { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
        public Nullable<int> Положительный_балл { get; set; }
    
        public virtual Дисциплины Дисциплины { get; set; }
        public virtual Специальности Специальности { get; set; }
    }
}
